rule Trojan_NavaShield_A_con {
    meta:
        threat_name = "Trojan/NavaShield.A!con"
        description = "Detects NavaShield"
        author = "Kybero Labs"

    strings:
        $s1 = "\\sim.exe"
        $s2 = "The setup files are corrupted. Please obtain a new copy of the program."
        $s3 = "inflate 1.1.4 Copyright 1995-2002 Mark Adler"
        $s4 = "Smart Install Maker v. 5.04"
        $s5 = "Welcome to installer Nava Shield"
        $s6 = "Copyright © 2015, Nava Labs"
        $s7 = "\\NavaShield.exe"
        $s8 = "Nava Shield 4.1 Installation"
        $s9 = "c:\\Nava Labs\\Nava Shield"
        $s10 = "Windows XP/2003 Server/Vista/2008 Server/7"
        $s11 = "\\UninstallNava.exe"
        $s12 = "\\NavaBridge Libs\\Browser Plugin.dll"
        $s13 = "\\NavaBridge Libs\\Internet Encodings.dll"
        $s14 = "\\NavaBridge Libs\\MD5.dll"
        $s15 = "\\NavaDebugger Libs\\MD5.dll"
        $s16 = "\\NavaDebugger.exe"
        $s17 = "\\NavaMod.dll"
        $s18 = "\\NavaShield Libs\\Appearance Pak.dll"
        $s19 = "\\NavaShield Libs\\Internet Encodings.dll"
        $s20 = "\\NavaStorage\\nava.dat"
        $s21 = "\\navig.dat"
        $s22 = "\\outlet.dat"
        $s23 = "\\store.dat"
        $s24 = "Welcome to the Nava Shield Setup Wizard"
        $s25 = "This wizard will guide you through the installation of Nava Shield."
        $s26 = "Setup will install Nava Shield in the following folder."
        $s27 = "Please wait while Nava Shield is being installed."
        $s28 = "Completing the Nava Shield Setup Wizard"
        $s29 = "Nava Shield has been installed on your computer."
        $s30 = "For installing Nava Shield on disk %s insufficiently free place."
        $s31 = "Please review the license terms before installing Nava Shield."
        $s32 = "Choose the folder in which to install Nava Shield."
        $s33 = "Choose a Start Menu Folder for the Nava Shield shortcuts."
        $s34 = "Please wait while Nava Shield is being installed."
        $s35 = "You must accept the agreement to install Nava Shield."
        $s36 = "Launch Nava Shield"
        $s37 = "Are you sure you want to quit Nava Shield?"
        $s38 = "Select the folder to install Nava Shield in:"
        $s39 = "Select any additional shortcuts for Nava Shield that you would like created by the installation:"
        $s40 = "A password is required to begin the installation of Nava Shield."
        $s41 = "Setup is now ready to begin installing Nava Shield on your computer."
        $s42 = "Nava Shield will be uninstalled from the following folder."
        $s43 = "Remove Nava Shield from your computer."
        $s44 = "Nava Shield was successfully removed."
        $s45 = "You really want to break removing Nava Shield?"

    condition:
        all of them
}
